### ISSUE TITLE
does it support webdav?

### ISSUE THREAD

**Issue by htogether** [EdoFede/nginx-php-fpm-Docker#1]
I have error log below, how do I enable it? could you include nginx-dav-ext-module for your next update?

nginx: [emerg] unknown directive "dav_ext_methods" in /etc/nginx/conf.d/mysite.conf:48

nginx: configuration file /etc/nginx/nginx.conf test failed

bash-5.0# nginx -V
nginx version: nginx/1.16.1
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --prefix=/var/lib/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --pid-path=/run/nginx/nginx.pid --lock-path=/run/nginx/nginx.lock --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --with-perl_modules_path=/usr/lib/perl5/vendor_perl --user=nginx --group=nginx --with-threads --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-http_perl_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-stream=dynamic --with-stream_ssl_module --with-stream_realip_module --with-stream_geoip_module=dynamic --with-stream_ssl_preread_module --add-dynamic-module=/home/buildozer/aports/main/nginx/src/njs-0.3.5/nginx --add-dynamic-module=/home/buildozer/aports/main/nginx/src/ngx_devel_kit-0.3.0 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/ngx_cache_purge-2.5 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/echo-nginx-module-0.61 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/ngx-fancyindex-0.4.3 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/headers-more-nginx-module-0.33 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/lua-nginx-module-0.10.15 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/lua-upstream-nginx-module-0.07 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/nchan-1.2.5 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/nginx-http-shibboleth-2.0.1 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/redis2-nginx-module-0.15 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/set-misc-nginx-module-0.32 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/nginx-upload-progress-module-0.9.2 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/nginx-upstream-fair-0.1.3 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/nginx-rtmp-module-1.2.1 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/nginx-vod-module-1.24 --add-dynamic-module=/home/buildozer/aports/main/nginx/src/ngx_http_geoip2_module-3.2
bash-5.0#

**Comment by EdoFede** [comment]
Hi,
it seems a missing module in the Alpine linux nginx package.
https://gitlab.alpinelinux.org/alpine/aports/-/issues/6964

Since it seems fixed, I'll try to update the docker image with the latest version.

Bye,
Edo

**Comment by htogether** [comment]
I modified dockerfile as below

added nginx-mod-http-dav-ext 

# Install required software
RUN	apk update && \
	apk --no-cache add \
		openssl \
		nginx \
		nginx-mod-http-dav-ext \   # added for webdav module
		php7 \
		php7-calendar \
		php7-common \
		php7-curl \
		php7-fpm \
		php7-json \
		php7-opcache \
		php7-posix \
		php7-xml && \
	rm -rf /var/cache/apk/*

COPY imageFiles/ /

added module in nginx.conf

user nginx;
worker_processes auto;
include /etc/nginx/modules/*.conf;  # added for webdav module

now, it works fine.

thank you

**Comment by EdoFede** [comment]
Thanks for you tip.
I've modified the file inserting the WebDAV module.

Could you confirm that it works for your case, by using the **master** tag (instead of latest) on docker?
If it works fine, I'll release a new version including this mod.

Thanks
